server:
  port: 8082
spring:
  #rabbitmq配置
  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 5672
  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 127.0.0.1
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #无密码
    password:
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  #mail邮件配置
  mail:
    host: smtp.163.com
    username: mlnothing21@163.com
    password: JOTUZGBFIMEKZRDB
    protocol: smtp
    default-encoding: utf-8
    port: 25